Server:
    SMTPServer: 127.0.0.1
    Pop3Server: 127.0.0.1
    SMTP: 2500
    POP3: 1100
    bufferSize: 51200
    max_file_size: 3145728 #bytes

Authentication:
    username: ducnhat24
    password: xxxx #can be anything, due to it is test server

Rules:
  - From: ["ahihi@testing.com", "ahuu@testing.com"]
    Folder: Project
  - Subject: ["urgent", "ASAP"]
    Folder: Important
  - Content: ["report", "meeting"]
    Folder: Work
  - Spam: ["virus", "hack", "crack"]
    Folder: Spam
Autoload:
  Time: 5 #seconds